[project]
name = "aws-llm-basic"
version = "0.1.0"
description = "basic example of how to use AWS Bedrock with Langchain"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.36.2",
    "langchain>=0.3.14",
    "langchain-aws>=0.2.11",
]
